### ISSUE TITLE
CHARSET=ANSI wird ignoriert und jeder Konvertierungsversuch schlägt fehl ohne erkennbaren Grund

### ISSUE THREAD

**Issue by CarlosHartmann** [KOST-CECO/csv2siard_toolset#3]
Hallo

Ich habe hier eine Reihe von CSV-Dateien mit Überschriften im ANSI-Format und ;-delimiter.

Im Log steht immer oben `[CHARSET] => ISO-8859-1` und weiter unten beim Transfer auch, obwohl ich in den Preferences ANSI angegeben habe:
```
CHARSET=ANSI
#CHARSET=ISO-8859-1
#CHARSET=UTF-8
```

ISO-8859-1 ist ja auskommentiert.

Das grössere Problem ist aber, dass die Konvertierung nicht funktioniert. Am Schluss des Logs steht immer:

```
ZIP SIARD file 
  addFile:   content/schema0/table0/table0.xml >crc32 >stuff 
  addFile:   content/schema0/table0/table0.xsd >stuff 
  addFolder: content/schema0/table0 
  addFile:   content/schema0/table1/table1.xml >crc32 >stuff 
  addFile:   content/schema0/table1/table1.xsd >stuff 
  addFolder: content/schema0/table1 
  addFile:   content/schema0/table2/table2.xml >crc32 >stuff 
  addFile:   content/schema0/table2/table2.xsd >stuff 
  addFolder: content/schema0/table2 
  addFile:   content/schema0/table3/table3.xml >crc32 >stuff 
  addFile:   content/schema0/table3/table3.xsd >stuff 
  addFolder: content/schema0/table3 
  addFolder: content/schema0 
  addFolder: content 
  addFolder: header 
  addFile:   header/metadata.xsd >stuff 
  addFile:   header/metadata.xml >stuff 
No SIARD file created
Conversion aborted
```

Ich habe csv2siard korrekt installiert und führe es auch als admin aus.

Mir fällt als mögliche Erklärung nur ein, dass der Ordner mit den CSV-Daten ein Leerzeichen enthält. Ich teste das bei Gelegenheit noch. Ausserdem ist kein Wert bei [CHECK_DATABASE_INTEGRITY] hinterlegt.

Ich melde das, weil wir bald eine Datenbank im .csv-Format zusammen mit einem unserer Partner archivieren werden. Eventuell brauchen wir dann mehr Hilfe.

Beste Grüsse
Carlos

**Comment by Chlara** [comment]
Hallo Carlos

Die Zeichensätze sollten nicht das Problem sein, da gewisse Zeichensätze  andere Zeichensätze ein schliessen: z.B. US-ASCII in ANSI und ISO-8859-1 enthalten, ASCII aber nicht in ANSI und ISO-8859-1. Evtl. könntest du es mal ohne CHARACTERSET verwenden. Das Problem mit Abbrechen müsste ich mit den Daten anschauen. Könntest du die Daten zur Verfügung stellen?

Liebi Grüessli      Claire

**Comment by CarlosHartmann** [comment]
Liebe Claire

Das stimmt, die Zeichensätze werden verlässlich erkannt. Ich hab das gerade mit anderen Beispieldaten geprüft. Das hat auch gezeigt, dass ich csv2siard grundsätzlich richtig installiert habe.

Die Daten sind leider sensibel. Wir müssten also allenfalls um die Daten herum arbeiten oder eine andere Lösugn finden. Das muss ich zuerst intern abklären. Ich melde mich dann nochmal bei Bedarf.

**Comment by Chlara** [comment]
csv2siard (deprecated)
Die Entwicklung von csv2siard wurde offiziell eingestellt.
