### ISSUE TITLE
Wie Primär- und Sekundärschlüssel angeben?

### ISSUE THREAD

**Issue by CarlosHartmann** [KOST-CECO/csv2siard_toolset#4]
Hallo,

Was mir im Anwendungshandbuch fehlt, ist eine Erläuterung wie ein db_model.xml auszusehen hat und welche Attribute ein <column>-Objekt haben kann. Ich habe mir das XML nämlich zuerst vom Programm generieren lassen, um es dann in einem zweiten Schritt anzupassen und zu verwenden.

Ich gehe mal davon aus, dass man in diesem Modell die Primär- und Fremdschlüssel festlegen kann. Ich finde aber keine Info dazu, wie das genau geht. Oder ob man die Schlüssel auch nachträglich irgendwie angeben kann.

Um Auskunft wäre ich dankbar!

**Comment by Chlara** [comment]
Lieber Carlos

Ja das fehlt im Handbuch, das müsste noch ergänzt werden. 
Du kannst das Modell anpassen. Als Grundlage lege ich dir mal das TAXAR Modell bei.
Ich habe die XML-Extension nach TXT geändert, damit es bei Github funktioniert.

Liebi Grüessli     Claire
[eCH-0233.5_a1-b_NP_model.txt](https://github.com/KOST-CECO/csv2siard_toolset/files/7076701/eCH-0233.5_a1-b_NP_model.txt)

**Comment by CarlosHartmann** [comment]
Liebe Claire

Danke, das beantwortet die Frage abschliessend.

Vielleicht waren die fehlenden Primärschlüssel das Problem im anderen Issue. Ich werde es gleich testen.

Beste Grüsse
Carlos
